= Backend service for Passel.
:source-highlighter: highlightjs

== Contributing

Note: you need to enter the vm and run
[source,sh]
----
sudo chmod a-x /sbin/initctl
----
before shared folders and provisioning through vagrant will work.

This is a workaround for link:https://github.com/mitchellh/vagrant/issues/5377[Issue #5377] with vagrant.

To make a virtualenv, run
[source, sh]
----
cd /vagrant
virtualenv venv
----

The rest of these instructions assume you have cd'd to /vagrant.

Make sure to activate it with
[source,sh]
----
source venv/bin/activate
----

Then, install the dependencies with
[source,sh]
----
pip install -r requirements.txt
----

You can start the server with
[source,sh]
----
python runserver.py
----

== License

Copyright (C) 2015 Aneesh Agrawal

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
